# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 500))
        self.listWidget.setStyleSheet("QListWidget{\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 85, 127);\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("QLabel{\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 127);\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("QLabel{\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 127);\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.request = QtWidgets.QPushButton(self.frame_2)
        self.request.setMinimumSize(QtCore.QSize(200, 40))
        self.request.setMaximumSize(QtCore.QSize(200, 16777215))
        self.request.setStyleSheet("\n"
"QPushButton{\n"
"image: url(:/boton/next_btn.png) ;\n"
"border:none;\n"
"/* color fondo*/\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0.0340909, x2:1, y2:0, stop:0 rgba(186, 186, 186, 255), stop:1 rgba(246, 246, 246, 255));\n"
"/* color texto*/\n"
"color:rgb(0,0,0);\n"
"/* bordes efecto 3d*/\n"
"border-left:1px solid rbg(0,0,0); \n"
"border-right:1px solid  rgb(0, 0, 0);\n"
"border-bottom:2px solid rgb(50,50,50); \n"
" /* redondeo esquinas*/\n"
"border-radius:20px;\n"
"/* fuente texto*/\n"
"font: 87 9pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"/* color fondo*/\n"
"background-color: qlineargradient(spread:pad, x1:0.511, y1:0.0340909, x2:1, y2:0, stop:0 rgba(126, 126, 126, 255), stop:1 rgba(200, 200, 200, 255));\n"
"/* color texto*/\n"
"color:rgb(0,0,0);\n"
"/* bordes efecto 3d*/\n"
"border:none;\n"
"border-left:1px solid rbg(0,0,0); \n"
"border-right:1px solid  rgb(0, 0, 0);\n"
"border-top:2px solid rgb(50,50,50); \n"
"}")
        self.request.setObjectName("request")
        self.verticalLayout.addWidget(self.request, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Postulante para ROBOTILSA SA"))
        self.request.setText(_translate("MainWindow", "REQUEST"))
import icono_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
