# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secundaria.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_second(object):
    def setupUi(self, second):
        second.setObjectName("second")
        second.resize(419, 463)
        self.centralwidget = QtWidgets.QWidget(second)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Berlin Sans FB Demi\";\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Berlin Sans FB Demi\";\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Berlin Sans FB Demi\";\n"
"}")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Berlin Sans FB Demi\";\n"
"}")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Berlin Sans FB Demi\";\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Berlin Sans FB Demi\";\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Berlin Sans FB Demi\";\n"
"}")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblheight = QtWidgets.QLabel(self.frame_2)
        self.lblheight.setStyleSheet("QLabel{\n"
"    font: 12pt \"Berlin Sans FB\";\n"
"}")
        self.lblheight.setObjectName("lblheight")
        self.verticalLayout_2.addWidget(self.lblheight)
        self.lblmass = QtWidgets.QLabel(self.frame_2)
        self.lblmass.setStyleSheet("QLabel{\n"
"    font: 12pt \"Berlin Sans FB\";\n"
"}")
        self.lblmass.setObjectName("lblmass")
        self.verticalLayout_2.addWidget(self.lblmass)
        self.lblhair_color = QtWidgets.QLabel(self.frame_2)
        self.lblhair_color.setStyleSheet("QLabel{\n"
"    font: 12pt \"Berlin Sans FB\";\n"
"}")
        self.lblhair_color.setObjectName("lblhair_color")
        self.verticalLayout_2.addWidget(self.lblhair_color)
        self.lblskin_color = QtWidgets.QLabel(self.frame_2)
        self.lblskin_color.setStyleSheet("QLabel{\n"
"    font: 12pt \"Berlin Sans FB\";\n"
"}")
        self.lblskin_color.setObjectName("lblskin_color")
        self.verticalLayout_2.addWidget(self.lblskin_color)
        self.lbleye_color = QtWidgets.QLabel(self.frame_2)
        self.lbleye_color.setStyleSheet("QLabel{\n"
"    font: 12pt \"Berlin Sans FB\";\n"
"}")
        self.lbleye_color.setObjectName("lbleye_color")
        self.verticalLayout_2.addWidget(self.lbleye_color)
        self.lblbirth_year = QtWidgets.QLabel(self.frame_2)
        self.lblbirth_year.setStyleSheet("QLabel{\n"
"    font: 12pt \"Berlin Sans FB\";\n"
"}")
        self.lblbirth_year.setObjectName("lblbirth_year")
        self.verticalLayout_2.addWidget(self.lblbirth_year)
        self.lblgender = QtWidgets.QLabel(self.frame_2)
        self.lblgender.setStyleSheet("QLabel{\n"
"    font: 12pt \"Berlin Sans FB\";\n"
"}")
        self.lblgender.setObjectName("lblgender")
        self.verticalLayout_2.addWidget(self.lblgender)
        self.horizontalLayout.addWidget(self.frame_2)
        second.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(second)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 21))
        self.menubar.setObjectName("menubar")
        second.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(second)
        self.statusbar.setObjectName("statusbar")
        second.setStatusBar(self.statusbar)

        self.retranslateUi(second)
        QtCore.QMetaObject.connectSlotsByName(second)

    def retranslateUi(self, second):
        _translate = QtCore.QCoreApplication.translate
        second.setWindowTitle(_translate("second", "Ventana Secundaria"))
        self.label_3.setText(_translate("second", "height:"))
        self.label_4.setText(_translate("second", "mass:"))
        self.label_6.setText(_translate("second", "hair_color:"))
        self.label_7.setText(_translate("second", "skin_color:"))
        self.label_5.setText(_translate("second", "eye_color:"))
        self.label.setText(_translate("second", "birth_year:"))
        self.label_8.setText(_translate("second", "gender:"))
        self.lblheight.setText(_translate("second", "lblheight"))
        self.lblmass.setText(_translate("second", "lblmass"))
        self.lblhair_color.setText(_translate("second", "lblhair_color"))
        self.lblskin_color.setText(_translate("second", "lblskin_color"))
        self.lbleye_color.setText(_translate("second", "lbleye_color"))
        self.lblbirth_year.setText(_translate("second", "lblbirth_year"))
        self.lblgender.setText(_translate("second", "lblgender"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    second = QtWidgets.QMainWindow()
    ui = Ui_second()
    ui.setupUi(second)
    second.show()
    sys.exit(app.exec_())
